import type { Metadata } from "next";
import Header from "../components/Header";
import "./globals.css";
import { JokeProvider } from "@/context/joke-context";

export const metadata: Metadata = {
  title: "Joke Generator",
  description: "Generated by pramuditha",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header />

        <JokeProvider>{children}</JokeProvider>
      </body>
    </html>
  );
}
